spring.application.name=PastExploreHub

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Use variables so Docker can override 'localhost' with 'db'
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pastexplorehub}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
# Match your compose password
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

server.port=8080


# spring.main.banner-mode=off


# Max size allowed for a single file
spring.servlet.multipart.max-file-size=10MB

# Max size allowed for the entire request (files + form data)
spring.servlet.multipart.max-request-size=15MB

# Set session timeout to 60 minutes (1 hour)
server.servlet.session.timeout=60m








